version: "3.9"

services:
  logviewer:
    image: subratade9ok/live-log-viewer
    container_name: logviewer
    ports:
      - "3000:3000"
    # env_file:
    #   - .env
    environment:
      - ALLOWED_IP=192.168.1.1/24
    volumes:
      - ./logs:/app/logs:ro
    restart: unless-stopped
